export const SET_SEARCHED_REFERENCES = 'SET_SEARCHED_REFERENCES';
export const ADD_RECIPE = 'ADD_RECIPE';

export const SET_ACTIVE_TAB = 'SET_ACTIVE_TAB';

export const SET_FETCHED_POSTS_LIST = 'SET_FETCHED_POSTS_LIST';
export const SET_FETCHED_POST = 'SET_FETCHED_POST';
